In [1]:
import pandas as pd

# ví dụ hai bảng (DataFrame)
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["A", "B", "C"]
})
df2 = pd.DataFrame({
    "id": [2, 3, 4],
    "score": [90, 80, 70]
})

# inner join (giống SQL INNER JOIN)
df_inner = pd.merge(df1, df2, on="id", how="inner")

# left join (giống SQL LEFT JOIN)
df_left = pd.merge(df1, df2, on="id", how="left")

# full outer join
df_full = pd.merge(df1, df2, on="id", how="outer")

# right join
df_right = pd.merge(df1, df2, on="id", how="right")

In [2]:
df_inner

   id name  score
0   2    B     90
1   3    C     80

In [3]:
df_left

   id name  score
0   1    A    NaN
1   2    B   90.0
2   3    C   80.0

In [4]:
df_full

   id name  score
0   1    A    NaN
1   2    B   90.0
2   3    C   80.0
3   4  NaN   70.0

In [5]:
df_right

   id name  score
0   2    B     90
1   3    C     80
2   4  NaN     70

In [7]:
dic = {
    "id": [1, 2, 3],
    "name": ["A", "B", "C"]
}

In [10]:
dic.items()

dict_items([('id', [1, 2, 3]), ('name', ['A', 'B', 'C'])])